spring.application.name=mobileApplication
spring.mvc.view.prefix=/WEB-INF/
spring.mvc.view.suffix=.jsp

spring.jpa.hibernate.ddl-auto=update
server.servlet.session.timeout=5m

resend.from=Smile Empress Dental Hub <noreply@mail.smileempressdentalhub.com>
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.thymeleaf.enabled=false